# Setup
title:        ChickenMayo's Blog
tagline:      ~ Records is the rule of memory ~
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       jinwoo lee
  url:        https://chickenmayo.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown